### ISSUE TITLE
cannot use app to add github OTP to yubikey 5C (APDU Error: 6a80)

### ISSUE THREAD

**Issue by phryneas** [Yubico/yubioath-android#106]
This worked fine with all other sites and I can also use the app to add the OTP to my old yubikey neo, but not to my new yubikey 5C.
The github key looks short, though. Could that be a factor?

**Comment by phryneas** [comment]
I took a look at the logs with `adb logcat`. Looks like something is crashing:

```
09-10 21:33:10.692 29384 29404 D yubioath: Requesting API...
09-10 21:33:10.695 29384 29404 D yubioath: USB device present
09-10 21:33:10.720 29384 29404 D yubioath: Got API, checking requests...
09-10 21:33:10.801 29384 29384 E yubioath: exception
09-10 21:33:10.801 29384 29384 E yubioath: com.yubico.yubioath.e.a: APDU Error: 6a80
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.d.e.a(Unknown Source:140)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.d.e.a(Unknown Source:19)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.d.e.a(Unknown Source:81)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.a.d.a(Unknown Source:165)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.add.AddCredentialViewModel$a.a(Unknown Source:7)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.add.AddCredentialViewModel$a.a(Unknown Source:2)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel$g$1.a(Unknown Source:30)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel$g$1.b(Unknown Source:19)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel$g$1.a(Unknown Source:4)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel.a(Unknown Source:266)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel.c(Unknown Source:191)
09-10 21:33:10.801 29384 29384 E yubioath:      at com.yubico.yubioath.ui.BaseViewModel$g$a.a(Unknown Source:31)
09-10 21:33:10.801 29384 29384 E yubioath:      at a.c.a.b.a.a.a(Unknown Source:9)
09-10 21:33:10.801 29384 29384 E yubioath:      at b.a.a.af.run(Unknown Source:118)
09-10 21:33:10.801 29384 29384 E yubioath:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-10 21:33:10.801 29384 29384 E yubioath:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-10 21:33:10.801 29384 29384 E yubioath:      at java.lang.Thread.run(Thread.java:764)
```

**Comment by phryneas** [comment]
Updating the authenticator to version 2.1.0 solved the problem
