### ISSUE TITLE
YubiKey 5Ci not working with LineageOS 16.x-based ROM

### ISSUE THREAD

**Issue by iynere** [Yubico/yubioath-android#117]
Getting "Error in YubiKey communication" whenever I plug in my YubiKey 5Ci (non-NFC) after opening Yubico Authenticator.

My exact ROM is Resurrection Remix 7.0.2, which is based on LineageOS 16 (Android Pie), running on an LG G5.

Have not been able to find anything in searching relevant XDA threads so far...

Here is some `logcat` output that I'm not sure how to parse:

**block 1**
```12-03 15:08:56.045  1488  2778 D UsbHostManager: USB device attached: vidpid 1050:0407 mfg/product/ver/serial Yubico/YubiKey OTP+FIDO+CCID/5.24/null hasAudio/HID/Storage: false/true/false
12-03 15:08:56.054  1488  2778 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=4176,mProductId=1031,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Yubico,mProductName=YubiKey OTP+FIDO+CCID,mVersion=5.24,mSerialNumber=null,mConfigurations=[
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=15,mInterfaces=[
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=3,mSubclass=1,mProtocol=1,mEndpoints=[
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=8,mInterval=10]]
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=4,mAttributes=3,mMaxPacketSize=64,mInterval=2]
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=132,mAttributes=3,mMaxPacketSize=64,mInterval=2]]
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=11,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=2,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=130,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:08:56.054  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=131,mAttributes=3,mMaxPacketSize=8,mInterval=32]]]]
12-03 15:08:56.084  1488  2438 I ActivityManager: Config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.25}
12-03 15:08:56.195  1488  2438 I ActivityManager: Override config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 1440, 2560) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.25} for displayId=0
12-03 15:08:56.337  1488  1785 E NotificationService: Suppressing notification from package by user request.
12-03 15:08:56.352  1488  2778 I ActivityManager: START u0 {act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000000 cmp=com.yubico.yubioath/.ui.main.MainActivity (has extras)} from uid 1000
12-03 15:08:56.417  1488  1488 W Looper  : Slow dispatch took 358ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@3ee7fa3 m=0
12-03 15:08:56.417  1488  1488 W Looper  : Slow delivery took 319ms main h=android.telephony.PhoneStateListener$1 c=null m=128
12-03 15:08:56.419  1488  1488 W Looper  : Drained
12-03 15:08:56.457  1488  2169 I UsbPortManager: ClientCallback: otg_default
12-03 15:08:56.457  1488  1782 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dual}, status=UsbPortStatus{connected=true, currentMode=dfp, currentPowerRole=source, currentDataRole=host, supportedRoleCombinations=[source:host]}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false
12-03 15:08:56.547  1488 10477 W NotificationService: Toast already killed. pkg=com.yubico.yubioath callback=android.app.ITransientNotification$Stub$Proxy@9e4ef6
12-03 15:08:56.946  1488  1745 I ActivityManager: Start proc 30589:com.android.mtp/u0a24 for broadcast com.android.mtp/.UsbIntentReceiver
12-03 15:08:58.586  1488  2438 I ActivityManager: Config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.26}
12-03 15:08:58.586  1488 10477 W NotificationService: Toast already killed. pkg=com.yubico.yubioath callback=android.app.ITransientNotification$Stub$Proxy@3790cfc
12-03 15:08:58.600  1488  2778 D UsbHostManager: Removed device at /dev/bus/usb/001/002: YubiKey OTP+FIDO+CCID
```

**block 2**
```12-03 15:51:05.696  1488  8328 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.yubico.yubioath/.ui.main.MainActivity} from uid 10103
12-03 15:51:05.996  1488  1745 I ActivityManager: Start proc 4400:com.yubico.yubioath/u0a110 for activity com.yubico.yubioath/.ui.main.MainActivity
12-03 15:51:06.022  4400  4400 E yubico.yubioat: Not starting debugger since process cannot load the jdwp agent.
12-03 15:51:06.161  3014  3014 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-03 15:51:06.306  4400  4400 D yubikit : Set USB listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:06.307  4400  4400 D yubikit : Set NFC listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:06.326  4400  4400 D OpenGLRenderer: Skia GL Pipeline
12-03 15:51:06.487  4400  4424 I Adreno  : QUALCOMM build                   : d7977ce, Ife855c4895
12-03 15:51:06.487  4400  4424 I Adreno  : Build Date                       : 08/21/18
12-03 15:51:06.487  4400  4424 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.00.00
12-03 15:51:06.487  4400  4424 I Adreno  : Local Branch                     : master
12-03 15:51:06.487  4400  4424 I Adreno  : Remote Branch                    :
12-03 15:51:06.487  4400  4424 I Adreno  : Remote Branch                    :
12-03 15:51:06.487  4400  4424 I Adreno  : Reconstruct Branch               :
12-03 15:51:06.487  4400  4424 I Adreno  : Build Config                     : S L 4.0.10 AArch64
12-03 15:51:06.488  4400  4424 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
12-03 15:51:06.496  4400  4424 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
12-03 15:51:06.507  4400  4424 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
12-03 15:51:06.508  4400  4424 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
12-03 15:51:06.509  4400  4424 I OpenGLRenderer: Initialized EGL, version 1.4
12-03 15:51:06.509  4400  4424 D OpenGLRenderer: Swap behavior 1
12-03 15:51:06.608  4400  4424 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
12-03 15:51:06.609  4400  4424 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
12-03 15:51:06.647  1488  2161 E system_server: No package ID ff found for ID 0xffffffff.
12-03 15:51:06.651  1488  1740 I ActivityManager: Displayed com.yubico.yubioath/.ui.main.MainActivity: +946ms
12-03 15:51:06.673   922  1300 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.yubico.yubioath#0
12-03 15:51:06.673   922  1300 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.yubico.yubioath#0
12-03 15:51:06.684   841   841 D QCOM PowerHAL: LAUNCH HINT: OFF
12-03 15:51:08.359   922  1302 W SurfaceFlinger: Attempting to destroy on removed layer: f149ba9 Toast#0
12-03 15:51:08.378   973  1178 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-03 15:51:08.380  1488  8328 W NotificationService: Toast already killed. pkg=com.yubico.yubioath callback=android.app.ITransientNotification$Stub$Proxy@185d2c7
12-03 15:51:10.779   842  1731 D sensors_hal_Ctx: poll:polldata:1, sensor:1, type:1, x:-0.212982 y:-0.637405 z:10.558624
12-03 15:51:10.780   842  1731 D sensors_hal_Util: waitForResponse: timeout=0
12-03 15:51:10.819   842  1731 D sensors_hal_Ctx: poll:polldata:1, sensor:1, type:1, x:-0.725342 y:-0.766693 z:10.053452
12-03 15:51:10.819   842  1731 D sensors_hal_Util: waitForResponse: timeout=0
12-03 15:51:10.858   842  1731 D sensors_hal_Ctx: poll:polldata:1, sensor:1, type:1, x:-0.833084 y:-0.548828 z:9.260971
12-03 15:51:10.859   842  1731 D sensors_hal_Util: waitForResponse: timeout=0
12-03 15:51:10.898   842  1731 D sensors_hal_Ctx: poll:polldata:1, sensor:1, type:1, x:0.208389 y:-0.235184 z:10.096542
12-03 15:51:10.898   842  1731 D sensors_hal_Util: waitForResponse: timeout=0
12-03 15:51:13.377  1488  2778 I UsbDescriptorParser: Unknown Descriptor len: 6 type:0x30
12-03 15:51:13.531  4040  4432 I FirebasePerformance: HTTP Method is null or invalid: null
12-03 15:51:13.531  4040  4432 I FirebasePerformance: Unable to process an HTTP request/response due to missing or invalid values. See earlier log statements for additional information on the specific invalid/missing values.
12-03 15:51:13.575  1488  9942 E LightsService: Light requested not available on this device. 2
12-03 15:51:13.879  1488  2778 W UsbDescriptor: UNDERRUN t:0x21 r: 9 < l: 54
12-03 15:51:13.884  1488  2778 D UsbHostManager: USB device attached: vidpid 1050:0407 mfg/product/ver/serial Yubico/YubiKey OTP+FIDO+CCID/5.24/null hasAudio/HID/Storage: false/true/false
12-03 15:51:13.888  1488  2778 D UsbDeviceDescriptor:   1 configs
12-03 15:51:13.890  1488  2778 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=4176,mProductId=1031,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Yubico,mProductName=YubiKey OTP+FIDO+CCID,mVersion=5.24,mSerialNumber=null,mConfigurations=[
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=15,mInterfaces=[
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=3,mSubclass=1,mProtocol=1,mEndpoints=[
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=8,mInterval=10]]
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=4,mAttributes=3,mMaxPacketSize=64,mInterval=2]
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=132,mAttributes=3,mMaxPacketSize=64,mInterval=2]]
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=11,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=2,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=130,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:51:13.890  1488  2778 D UsbHostManager: UsbEndpoint[mAddress=131,mAttributes=3,mMaxPacketSize=8,mInterval=32]]]]
12-03 15:51:13.899  1488  2439 D EventHub: No input device configuration file found for device 'Yubico YubiKey OTP+FIDO+CCID'.
12-03 15:51:13.916  1488  2439 I EventHub: wakeMechanism=EPOLLWAKEUP, usingClockIoctl=true
12-03 15:51:13.916  1488  2439 I EventHub: New device: id=16, fd=289, path='/dev/input/event6', name='Yubico YubiKey OTP+FIDO+CCID', classes=0x80000003, configuration='', keyLayout='/system/usr/keylayout/Generic.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false,
12-03 15:51:13.917  1488  2439 I InputReader: Device added: id=16, name='Yubico YubiKey OTP+FIDO+CCID', sources=0x00000101
12-03 15:51:13.919  1488  2438 I ActivityManager: Config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.27}
12-03 15:51:14.022  1488  2438 I ActivityManager: Override config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 1440, 2560) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.27} for displayId=0
12-03 15:51:14.048  1488  8328 W system_server: Long monitor contention with owner InputDispatcher (2438) at boolean com.android.server.am.ActivityManagerService.updateDisplayOverrideConfiguration(android.content.res.Configuration, int)(ActivityManagerService.java:22907) waiters=0 in int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int) for 124ms
12-03 15:51:14.055  1488  1785 E NotificationService: Suppressing notification from package by user request.
12-03 15:51:14.092  4040  4432 I FirebasePerformance: HTTP Method is null or invalid: null
12-03 15:51:14.092  4040  4432 I FirebasePerformance: Unable to process an HTTP request/response due to missing or invalid values. See earlier log statements for additional information on the specific invalid/missing values.
12-03 15:51:14.115  2842  2842 W GoogleInputMethodService: onConfigurationChanged() : NewConfig = {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.27}
12-03 15:51:14.129  1488  2778 I ActivityManager: START u0 {act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000000 cmp=com.yubico.yubioath/.ui.main.MainActivity (has extras)} from uid 1000
12-03 15:51:14.136  4400  4400 D yubikit : Set USB listener: null
12-03 15:51:14.136  4400  4400 D yubikit : Set NFC listener: null
12-03 15:51:14.137  3840  3858 E NfcService: setReaderMode() called while NFC is not enabled.
12-03 15:51:14.150  4400  4400 D yubikit : Set USB listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:14.150  4400  4400 D yubikit : Set NFC listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:14.151  4400  4400 D yubikit : Set USB listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:14.152  1488  1488 W Looper  : Slow dispatch took 260ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@396a1ea m=0
12-03 15:51:14.153  1488  1488 D SmartPixelsService: Screen orientation changed, updating window layout
12-03 15:51:14.159  4400  4418 D yubikit : Has permission for:UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=4176,mProductId=1031,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Yubico,mProductName=YubiKey OTP+FIDO+CCID,mVersion=5.24,mSerialNumber=null,mConfigurations=[
12-03 15:51:14.159  4400  4418 D yubikit : UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=15,mInterfaces=[
12-03 15:51:14.159  4400  4418 D yubikit : UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=3,mSubclass=1,mProtocol=1,mEndpoints=[
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=8,mInterval=10]]
12-03 15:51:14.159  4400  4418 D yubikit : UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=4,mAttributes=3,mMaxPacketSize=64,mInterval=2]
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=132,mAttributes=3,mMaxPacketSize=64,mInterval=2]]
12-03 15:51:14.159  4400  4418 D yubikit : UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=11,mSubclass=0,mProtocol=0,mEndpoints=[
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=2,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=130,mAttributes=2,mMaxPacketSize=64,mInterval=0]
12-03 15:51:14.159  4400  4418 D yubikit : UsbEndpoint[mAddress=131,mAttributes=3,mMaxPacketSize=8,mInterval=32]]]]
12-03 15:51:14.178  4400  4418 D UsbDeviceConnectionJNI: close
12-03 15:51:14.179  4400  4418 E yubioath: Error using OathClient
12-03 15:51:14.179  4400  4418 E yubioath: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
12-03 15:51:14.179  4400  4418 E yubioath: 	at java.util.Collections$SingletonList.get(Collections.java:4863)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.c.f.<init>(Unknown Source:89)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.b.c(Unknown Source:10)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.b.c(Unknown Source:0)
12-03 15:51:14.179  4400  4418 E yubioath: 	at c.m.getValue(Unknown Source:22)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.a.n(Unknown Source:7)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.a.a(Unknown Source:182)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.a.a(Unknown Source:0)
12-03 15:51:14.179  4400  4418 E yubioath: 	at com.yubico.yubioath.ui.main.MainActivity.a(Unknown Source:53)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.b.e.g.c(Unknown Source:40)
12-03 15:51:14.179  4400  4418 E yubioath: 	at c.c.b.a.a.a(Unknown Source:9)
12-03 15:51:14.179  4400  4418 E yubioath: 	at kotlinx.coroutines.U.run(Unknown Source:65)
12-03 15:51:14.179  4400  4418 E yubioath: 	at android.os.Handler.handleCallback(Handler.java:873)
12-03 15:51:14.179  4400  4418 E yubioath: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-03 15:51:14.179  4400  4418 E yubioath: 	at android.os.Looper.loop(Looper.java:193)
12-03 15:51:14.179  4400  4418 E yubioath: 	at b.c.a.a.run(Unknown Source:12)
12-03 15:51:14.179  4400  4418 E yubioath: 	at java.lang.Thread.run(Thread.java:764)
12-03 15:51:14.184  2842  2842 W KeyboardModeManager: setInputView() : inputView = null
12-03 15:51:14.209  2842  2842 I DeviceStatusMonitor: onReceive() : Action = android.intent.action.CONFIGURATION_CHANGED
12-03 15:51:14.209  2842  2842 I ConfigurationNotification: Get device mode by ui mode:1 and smallestScreenWidthDp:411
12-03 15:51:14.209  2842  2842 I chatty  : uid=10082(com.google.android.inputmethod.latin) identical 2 lines
12-03 15:51:14.210  2842  2842 I ConfigurationNotification: Get device mode by ui mode:1 and smallestScreenWidthDp:411
12-03 15:51:14.243  1488  2161 E system_server: No package ID ff found for ID 0xffffffff.
12-03 15:51:14.270   844  2566 E android.hardware.usb@1.0-service: uevent received SUBSYSTEM=dual_role_usb
12-03 15:51:14.270   844  2566 I android.hardware.usb@1.0-service: otg_default
12-03 15:51:14.271   844  2566 I android.hardware.usb@1.0-service: canChangeMode: 0 canChagedata: 0 canChangePower:0
12-03 15:51:14.277  1488  2948 I UsbPortManager: ClientCallback: otg_default
12-03 15:51:14.278  1488  1782 I UsbPortManager: USB port changed: port=UsbPort{id=otg_default, supportedModes=dual}, status=UsbPortStatus{connected=true, currentMode=dfp, currentPowerRole=source, currentDataRole=host, supportedRoleCombinations=[source:host]}, canChangeMode=false, canChangePowerRole=false, canChangeDataRole=false
12-03 15:51:14.292  4062  4078 I reenify:servic: Background concurrent copying GC freed 207577(9MB) AllocSpace objects, 50(1832KB) LOS objects, 83% free, 2MB/14MB, paused 162us total 116.745ms
12-03 15:51:14.380  3014  3014 D vol.VolumeDialogImpl: addExistingRows
12-03 15:51:14.414  1488  1745 I ActivityManager: Start proc 4435:com.android.mtp/u0a24 for broadcast com.android.mtp/.UsbIntentReceiver
12-03 15:51:14.432  4435  4435 E com.android.mt: Not starting debugger since process cannot load the jdwp agent.
12-03 15:51:14.468   922  3213 W SurfaceFlinger: Attempting to destroy on removed layer: 65b1a3d DockedStackDivider#0
12-03 15:51:14.495  3014  3014 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-03 15:51:15.932  1488  1745 I ActivityManager: Start proc 4449:com.google.android.setupwizard/u0a14 for broadcast com.google.android.setupwizard/.restore.UsbAttachedReceiver
12-03 15:51:14.512  3014  3014 I chatty  : uid=10018(com.android.systemui) identical 5 lines
12-03 15:51:14.514  3014  3014 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-03 15:51:15.954  4449  4449 E oid.setupwizar: Not starting debugger since process cannot load the jdwp agent.
12-03 15:51:16.077  4449  4449 W oid.setupwizar: JIT profile information will not be recorded: profile file does not exits.
12-03 15:51:16.122  4449  4449 I SetupWizard: [FrpHelper] Start loading FRP status
12-03 15:51:16.151  4449  4449 I SetupWizard: [ComponentLifecycleCallback] Enabling all components
12-03 15:51:16.181  1488 11918 D PackageManager: Ignoring attempt to set enabled state of disabled component com.google.android.setupwizard/com.google.android.setupwizard.time.DateTimeCheck
12-03 15:51:16.203   922  3213 W SurfaceFlinger: Attempting to destroy on removed layer: a8f6a8d Toast#0
12-03 15:51:16.215   973  1178 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-03 15:51:16.220  1488  5284 W NotificationService: Toast already killed. pkg=com.yubico.yubioath callback=android.app.ITransientNotification$Stub$Proxy@b2642cb
12-03 15:51:16.257  3408  3408 W ChimeraUtils: Non Chimera context
12-03 15:51:16.301  1488  5284 E NotificationService: Suppressing notification from package by user request.
12-03 15:51:16.257  3408  3408 W ChimeraUtils: Non Chimera context
12-03 15:51:16.326  4449  4449 I SetupWizard: [PreDeferredServiceScheduler] Scheduled job#2651 to run
12-03 15:51:16.516  1488  5284 I WifiService: startScan uid=10014
12-03 15:51:16.561  1488  7920 I ActivityManager: Killing 14987:com.google.process.gapps/u0a33 (adj 906): empty #17
12-03 15:51:16.563  1488  1746 W libprocessgroup: kill(-14987, 9) failed: No such process
12-03 15:51:16.603   765   765 I Zygote  : Process 14987 exited due to signal (9)
12-03 15:51:16.606  1488  1746 W libprocessgroup: kill(-14987, 9) failed: No such process
12-03 15:51:16.607  1488  1746 I libprocessgroup: Successfully killed process cgroup uid 10033 pid 14987 in 43ms
12-03 15:51:16.637  4449  4449 I SetupWizard: [FrpHelper] frpStatus=supported=true challengeRequired=false duration=513ms
12-03 15:51:16.813  1488  1502 I system_server: Background concurrent copying GC freed 365036(14MB) AllocSpace objects, 54(3MB) LOS objects, 42% free, 25MB/43MB, paused 527us total 423.035ms
12-03 15:51:17.251  1488  2439 I EventHub: Removing device Yubico YubiKey OTP+FIDO+CCID due to epoll hang-up event.
12-03 15:51:17.251  1488  2439 I EventHub: Removed device: path=/dev/input/event6 name=Yubico YubiKey OTP+FIDO+CCID id=16 fd=289 classes=0x80000003
12-03 15:51:17.254  1488  2439 I InputReader: Device removed: id=16, name='Yubico YubiKey OTP+FIDO+CCID', sources=0x00000101
12-03 15:51:17.255  1488  2439 I EventHub: Removing device '/dev/input/event6' due to inotify event
12-03 15:51:17.256  1488  2438 I ActivityManager: Config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.28}
12-03 15:51:17.348  1488  1488 D SmartPixelsService: Screen orientation changed, updating window layout
12-03 15:51:17.349  1488  2438 I ActivityManager: Override config changes=30 {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1440, 2560) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.28} for displayId=0
12-03 15:51:17.369  1488  2778 D UsbHostManager: Removed device at /dev/bus/usb/001/002: YubiKey OTP+FIDO+CCID
12-03 15:51:17.369  1488  2778 I UsbAlsaManager: USB Audio Device Removed: null
12-03 15:51:17.371  2842  2842 W GoogleInputMethodService: onConfigurationChanged() : NewConfig = {1.3 310mcc260mnc [en_US,iw_IL] ldltr sw411dp w411dp h707dp 560dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1440, 2560) mWindowingMode=fullscreen mActivityType=undefined} s.28}
12-03 15:51:17.383  2842  2842 W KeyboardModeManager: setInputView() : inputView = null
12-03 15:51:17.397  1488  1782 D UsbDeviceManager: push notification:Charging connected device via USB
12-03 15:51:17.403  2842  2842 I DeviceStatusMonitor: onReceive() : Action = android.intent.action.CONFIGURATION_CHANGED
12-03 15:51:17.403  2842  2842 I ConfigurationNotification: Get device mode by ui mode:1 and smallestScreenWidthDp:411
12-03 15:51:17.403  2842  2842 I chatty  : uid=10082(com.google.android.inputmethod.latin) identical 2 lines
12-03 15:51:17.403  2842  2842 I ConfigurationNotification: Get device mode by ui mode:1 and smallestScreenWidthDp:411
12-03 15:51:17.663  3014  3014 D vol.VolumeDialogImpl: addExistingRows
12-03 15:51:17.692  4400  4400 D yubikit : Set USB listener: com.yubico.yubioath.ui.main.MainActivity@fab283e
12-03 15:51:17.701  1488  1785 E system_server: No package ID ff found for ID 0xffffffff.
```

**Comment by imakhalova** [comment]
Thank you for you issue report.
Since the code is obfuscated it's not clear what is failing..
If it's possible can you please build this app from sources and run on your device that will give stacktrace in logcat for the exception that you have.
In meanwhile we're looking for the root cause of this issue, there is another project that you can try:
https://github.com/YubicoLabs/yubikit-android/
This app has OATH demo you can select in Nav drawer, which is very light version of Authenticator.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. We have released a new version of the app, please verify whether the communication issues are still present in the new version and eventually open a new issue in the new repository.
